name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to